# Use the base image with Azure CLI and Python installed
FROM mcr.microsoft.com/azure-cli:2.60.0

# This version of the az-cli image comes with Python 3.11.9
# Both the azure-cli:2.60.0 image and Python version 3.11.9 have been thoroughly tested and certified to function with all the scripts in this repo.
# Changing the image or python version is possible, but untested and therefore not supported. Proceed at your own risk.

# Avoid prompts and set noninteractive installation
ENV DEBIAN_FRONTEND=noninteractive

# Install necessary packages using Alpine's package manager without caching the index
RUN apk add --no-cache \
    git \
    curl \
    jq \
    util-linux \
    python3 \
    py3-pip \
    bash \
    sed \
    openssh-client \
    coreutils \
    openssl \
    dnsmasq

# Install Docker and OpenRC
RUN apk add --update docker openrc

# Enable Docker to start at boot
RUN rc-update add docker boot
RUN apk add --no-cache gcc python3-dev musl-dev linux-headers



# Set the working directory
WORKDIR /workspace

# Set the default shell to bash
SHELL ["/bin/bash", "-c"]